[versions]
flywheel = "1.0.6-41"
mixinextras = "0.4.1"
ponder = "1.0.85+mc1.21.1"

[libraries]
cdg = "maven.modrinth:create-diesel-generators:1.21.1-1.3.7"
cca = "maven.modrinth:createaddition:neoforge-1.21.1-1.5.8"
create = "com.simibubi.create:create-1.21.1:6.0.10-280"
copycats = "com.copycatsplus:copycats:3.0.4+mc.1.21.1-neoforge"
embeddium = "maven.modrinth:embeddium:1.0.15+mc1.21.1"
flywheel-neoforge-api = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
flywheel-neoforge = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }
geckolib-neoforge = "software.bernie.geckolib:geckolib-neoforge-1.21.1:4.7.2"
jcpp = "org.anarres:jcpp:1.4.14"
jei-neoforge = "mezz.jei:jei-1.21.1-neoforge:19.25.0.322"
kubejs = "dev.latvian.mods:kubejs-neoforge:2101.7.2-build.285"
kubejs-create = "maven.modrinth:kubejs-create:2101.3.1-build.18"
mclib = "com.eliotlash.mclib:mclib:20"
minecraft = "com.mojang:minecraft:1.21.1"
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras-neoforge = { module = "io.github.llamalad7:mixinextras-neoforge", version.ref = "mixinextras" }
neoforge = "net.neoforged:neoforge:21.1.219"
ponder-neoforge = { module = "net.createmod.ponder:ponder-neoforge", version.ref = "ponder" }
registrate = "com.tterrag.registrate:Registrate:MC1.21-1.3.0+67"
tfmg = "maven.modrinth:create-tfmg:1.1.0e"
